package com.sergimarrahyarenas.bloodstats.model.characterequipment

data class EquippedItem(
    val armor: Armor,
    val binding: Binding,
    val bonus_list: List<Int>,
    val context: Int,
    val durability: Durability,
    val enchantments: List<Enchantment>,
    val inventory_type: InventoryType,
    val is_subclass_hidden: Boolean,
    val item: ItemXX,
    val item_class: ItemClass,
    val item_subclass: ItemSubclass,
    val level: Level,
    val limit_category: String,
    val media: Media,
    val modified_appearance_id: Int,
    val modified_crafting_stat: List<ModifiedCraftingStat>,
    val name: String,
    val name_description: NameDescription,
    val quality: Quality,
    val quantity: Int,
    val requirements: Requirements,
    val sell_price: SellPrice,
    val `set`: Set,
    val slot: Slot,
    val sockets: List<Socket>,
    val spells: List<Spell>,
    val stats: List<Stat>,
    val transmog: Transmog,
    val unique_equipped: String,
    val weapon: Weapon
)