package com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics

data class CharacterStatistics(
    val _links: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Links? = null,
    val agility: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Agility? = null,
    val armor: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Armor,
    val attack_power: Int,
    val avoidance: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Avoidance,
    val block: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Block,
    val bonus_armor: Int,
    val character: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Character,
    val dodge: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Dodge,
    val health: Int,
    val intellect: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Intellect,
    val lifesteal: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Lifesteal,
    val main_hand_damage_max: Double,
    val main_hand_damage_min: Double,
    val main_hand_dps: Double,
    val main_hand_speed: Double,
    val mana_regen: Int,
    val mana_regen_combat: Int,
    val mastery: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Mastery,
    val melee_crit: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.MeleeCrit,
    val melee_haste: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.MeleeHaste,
    val off_hand_damage_max: Double,
    val off_hand_damage_min: Double,
    val off_hand_dps: Double,
    val off_hand_speed: Double,
    val parry: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Parry,
    val power: Int,
    val power_type: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.PowerType,
    val ranged_crit: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.RangedCrit,
    val ranged_haste: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.RangedHaste,
    val speed: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Speed,
    val spell_crit: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.SpellCrit,
    val spell_haste: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.SpellHaste,
    val spell_penetration: Int,
    val spell_power: Int,
    val stamina: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Stamina,
    val strength: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterstatistics.Strength,
    val versatility: Int,
    val versatility_damage_done_bonus: Double,
    val versatility_damage_taken_bonus: Double,
    val versatility_healing_done_bonus: Double
)