package com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment

data class EquippedItem(
    val armor: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Armor,
    val binding: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Binding,
    val bonus_list: List<Int>,
    val context: Int,
    val durability: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Durability,
    val enchantments: List<com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Enchantment>,
    val inventory_type: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.InventoryType,
    val is_subclass_hidden: Boolean,
    val item: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.ItemXX,
    val item_class: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.ItemClass,
    val item_subclass: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.ItemSubclass,
    val level: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Level,
    val limit_category: String,
    val media: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Media,
    val modified_appearance_id: Int,
    val modified_crafting_stat: List<com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.ModifiedCraftingStat>,
    val name: String,
    val name_description: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.NameDescription,
    val quality: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Quality,
    val quantity: Int,
    val requirements: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Requirements,
    val sell_price: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.SellPrice,
    val `set`: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Set,
    val slot: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Slot,
    val sockets: List<com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Socket>,
    val spells: List<com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Spell>,
    val stats: List<com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Stat>,
    val transmog: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Transmog,
    val unique_equipped: String,
    val weapon: com.sergimarrahyarenas.bloodstats.model.blizzardmodels.characterequipment.Weapon
)