package com.sergimarrahyarenas.bloodstats.utils

object Constants {
    const val CLIENT_ID = "286817623f474bcface004dc20313828"
    const val CLIENT_SECRET = "UCysV7ZsseanapD1lOfVg7FRTpCj2GXl"
    const val BEARER = "Bearer"
    const val BASE_ACCESS_TOKEN_URL = "https://oauth.battle.net/"
    const val BASE_PROFILE_URL = "https://eu.api.blizzard.com/profile/wow/"
    const val BASE_DATA_URL = "https://eu.api.blizzard.com/data/wow/"
    const val CHARACTER_MEDIA = "character-media"
    const val ENCOUNTERS = "encounters"
    const val DUNGEONS = "dungeons"
    const val MYTHIC_KEYSTONE_PROFILE = "mythic-keystone-profile"
    const val ROSTER = "roster"
    const val SPECIALIZATION = "specializations"
    const val ITEM_MEDIA = "item-media"
    const val EQUIPMENT = "equipment"
    const val STATISTICS = "statistics"
    const val GRANT_TYPE = "client_credentials"
    const val NAMESPACE = "profile-eu"
    const val DYNAMIC_NAMESPACE = "dynamic-eu"
    const val STATIC_NAMESPACE = "static-eu"
    const val LOCALE_ES = "es_ES"
    const val LOCALE_EN = "en_EN"
    const val LOCALE_IT = "it_IT"
}